# Set in this file the parameters for the simulation

# Model to use
useCoupled:   True 
useDecoupled: False

# Control
useControl: False
# Select the control to use
usePositiveControl: True

# Timestep size
dt: 0.001

# Number of iterations
it: 15000

# Plot config
plot:             True    # if True, it plots every plotSize iterations. If false, every plot is disabled.
plotEvolution:    False
plotStateSpace:   False
plotVectorField:  False
plotEigenvalues:  False
plotStabilityXY:  False    # Generate plot with stability as a function of X, Y
resetPlotBuffer:  False   # Set to False if running comparison among different IC
plot4dLimitCycle: True
plotSize: 30000   # number of timesteps to plot together

# Print config (in terminal)
printEquilibria:  False

# Initial conditions
# System 1
x0: 20.0   # prey 1: Rabbit
y0: 10.0   # predator 1: Burmese Python
# System 2
z0: 20.0   # prey 2: Deer
w0: 10.0   # predator 2: Eagle

# Control Parameters

# Positive Control: dx/dt = diag(x)*(A*(x-e)+k*u)
k1: 1.0
k2: 1.0
k3: 1.0
k4: 1.0
sigma:  1.0

# Parameters for coupled system
# The reference Lotka-Volterra equations are:
# dxi/dt = xi(bi - sum_j(aij * xj))    ,    i=1,_,n
# In the 4 species case, there are 20 parameters to be set (4 in b and 4x4 in a)

b1:   4.0
b2:  -1.0
b3:   2.0
b4:   -1

# If X and Y are defined, they overwrite the following values
# a23=-X, a32=X/2
# a24=-Y, a42=Y/2
X:    0.28
Y:    0.24

# All other parameters which we don't study
a11:  0.0 #Effect on rabbit for rabbit/rabbit
a12:  0.5 #Effect on rabbit for rabbit/snake
a13:  0.0  #Effect on rabbit for rabbit/deer
a14:  0.0  #Effect on rabbit for rabbit/eagle
a21:  -1.0 #Effect on snake for snake/rabbit
a22:  0.0 #Effect on snake for snake/snake
a23:  -0.28 #Effect on snake for snake/deer
a24:  -0.24 #Effect on snake for snake/eagle
a31:  0 #Effect on deer for deer/rabbit
a32:  0.14 #Effect on deer for deer/snake
a33:  0.0 #Effect on deer for deer/deer
a34:  0.5 #Effect on deer for deer/eagle
a41:  0.0 #Effect on eagle for eagle/rabbit
a42:  0.12 #Effect on eagle for eagle/snake (Here predator prey can interchange, might be interesting to see what happens)
a43:  -1 #Effect on eagle for eagle/deer
a44:  0 #Effect on eagle for eagle/eagle

# Parameters for decoupled system
# The reference Lotka-Volterra equations are:
# Prey:     dx/dt = alpha*x - beta*x*y
# Predator: dy/dt = -delta*x*y + gamma*y
# System 1
alpha1:  4.0
beta1:   0.5
gamma1:  -1.0 # negative sign for the predator
delta1:  -1.0 # negative sign for the predator
# System 2
alpha2:  3.0
beta2:   0.5
gamma2:  -1.0
delta2:  -1.0

# Integration method
useEulerForward:  False
useRK4:           True

# Comparison among different Initial Conditions
compareIC:  True
n_IC: 3 # number of IC to try out

# System 1
x1: 10.0   # prey 1: Rabbit
y1: 10.0   # predator 1: Burmese Python
# System 2
z1: 20.0   # prey 2: Deer
w1: 10.0   # predator 2: Eagle

# System 1
x2: 50.0   # prey 1: Rabbit
y2: 20.0   # predator 1: Burmese Python
# System 2
z2: 50.0   # prey 2: Deer
w2: 10.0   # predator 2: Eagle

# System 1
x3: 20.0   # prey 1: Rabbit
y3: 20.0   # predator 1: Burmese Python
# System 2
z3: 20.0   # prey 2: Deer
w3: 10.0   # predator 2: Eagle

# Stability plot for different X and Y
stability_discretization: 15


# ESTIMATOR (EKF)
noisyDynamics:  True  # has to be true if using an estimator.
# note that the dynamics are actually noisy in the estimator class, not in the dynamics class

Q:  0.4 # Standard deviation of the states
R:  0.3 # Standard deviation of the measurements