# Set in this file the parameters for the simulation

# Model to use
useCoupled:   True
useDecoupled: False

# Timestep size
dt: 0.001

# Number of iterations
it: 300000

# Plot config
plot:             True    # if True, it plots every plotSize iterations. If false, every plot is disabled.
plotEvolution:    True
plotStateSpace:   True
plotVectorField:  False
plotSize: 200000     # number of timesteps to plot together

# Initial conditions
# System 1
x0: 20.0   # prey 1: Rabbit
y0: 10.0   # predator 1: Burmese Python
# System 2
z0: 20.0   # prey 2: Deer
w0: 10.0   # predator 2: Eagle

# Parameters for coupled system
# The reference Lotka-Volterra equations are:
# dxi/dt = xi(bi - sum_j(aij * xj))    ,    i=1,_,n
# In the 4 species case, there are 20 parameters to be set (4 in b and 4x4 in a)

# Baseline parameters from separate predator-prey systems
b1:   4.0 #Rabbit reproduction rate
b2:  -1.0 #Snake death rate
b3:   2.0 #Deer reproduction rate
b4:  -1.0 #Eagle death rate
a12:  0.5 #Effect on rabbit for rabbit/snake
a21:  -1.0 #Effect on snake for snake/rabbit
a34:  0.5 #Effect on deer for deer/eagle
a43:  -1.0 #Effect on eagle for eagle/deer

# Parameters to study
a23:  -0.5 #Effect on snake for snake/deer
a32:  0.25 #Effect on deer for snake/deer
a24:  -0.25 #Effect on snake for snake/eagle
a42:  0.125 #Effect on eagle for snake/eagle 


# All other parameters which we don't study
a11:  0.0 #Effect on rabbit for rabbit/rabbit
a13:  0.0  #Effect on rabbit for rabbit/deer 
a14:  0.0  #Effect on rabbit for rabbit/eagle 
a22:  0.0 #Effect on snake for snake/snake
a31:  0.0 #Effect on deer for deer/rabbit
a33:  0.0 #Effect on deer for deer/deer
a41:  0.0 #Effect on eagle for eagle/rabbit
a44:  0.0 #Effect on eagle for eagle/eagle

# Parameters for decoupled system
# The reference Lotka-Volterra equations are:
# Prey:     dx/dt = alpha*x - beta*x*y
# Predator: dy/dt = -delta*x*y + gamma*y
# System 1
alpha1:  4.0
beta1:   0.5
gamma1:  -1.0 # negative sign for the predator
delta1:  -1.0 # negative sign for the predator
# System 2
alpha2:  3.0
beta2:   0.5
gamma2:  -1.0
delta2:  -1.0

# Integration method
useEulerForward:  False
useRK4:           True